# Generated by Django 5.0.2 on 2024-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandsnap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='has_skills',
        ),
        migrations.AddField(
            model_name='artist',
            name='skills',
            field=models.ManyToManyField(to='bandsnap.skill'),
        ),
    ]
