# Generated by Django 5.0.2 on 2024-03-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandsnap', '0002_remove_artist_has_skills_artist_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='band',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
