# Generated by Django 5.0.2 on 2024-03-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandsnap', '0005_remove_userprofile_website_userprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
    ]
