# Generated by Django 5.0.2 on 2024-03-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandsnap', '0006_remove_userprofile_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
